### ISSUE TITLE
🐛 [Bug report]: create-play not working with lower node versions

### ISSUE THREAD

**Issue by murtuzaalisurti** [atapas/react-play#46]
**Describe the bug**
In lower node versions (< 16), there is an issue with creating a new play by running `yarn create-play` or `npm run create-play`. The script works fine with node version `16.14.0`.

**To Reproduce**
1. Using `nvm` try to use a node version lower than `16` (probably `14`) and run `npm run create-play` or `yarn create-play`.
2. Fill necessary details.
3. An error might be evident stating `trim(...).replaceAll()` is not a function!

**Expected behavior**
To create a play

**Screenshots**
![Code_jzJJI3SB2p](https://user-images.githubusercontent.com/68743212/163792224-d3c65ba8-e880-4ef7-a51c-d89306c4476b.jpg)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]

**Comment by 6km** [comment]
Node.js v14 has V8 8.4 but `replaceAll` was added to V8 8.5 (which is used by node.js v15).
This means that you can't use `.replaceAll` if your Node.js version is lower that 15.

Can you reproduce this with node.js v15?
